version: '3'
tasks:
    module:
        cmds:
            - go run cmd/main.go dump
            - go run cmd/main.go module {{.CLI_ARGS}}
            - go mod tidy
    run:
        cmds:
            - go run cmd/main.go dump
            - go run cmd/main.go run
    clean:
        cmds:
            - go mod tidy
            - go run cmd/main.go dump
    update:
        cmds:
            - go get -u
            - go run cmd/main.go dump
    dump:
        cmds:
            - go run cmd/main.go dump
    generate:
        cmds:
            - go run cmd/main.go dump
            - sh proto_gen.sh
