version: '3'
tasks:
    module:
        cmds:
            - go run cmds/module/main.go {{.CLI_ARGS}}
    serve:
        cmds:
            - go run cmds/dic/main.go
            - go run cmds/app/main.go
    clean:
        cmds:
            - go mod tidy
    update:
        cmds:
            - go get -u
    generate:
        cmds:
            - sh proto_gen.sh
